### ISSUE TITLE
Magnifying icon looks squished

### ISSUE THREAD

**Issue by Keith94** [dempfi/ayu#129]
In command palette, magnifying glass icon is possibly displayed too narrow or blurry.

![image](https://user-images.githubusercontent.com/5490615/28205419-cdd5f8ae-6836-11e7-8d93-7b9b9e8cb7d7.png)

**Comment by Allegathor** [comment]
I have the same issue. I think it occurs only on Windows.

**Comment by Allegathor** [comment]
Hello, @dempfi. Thank you for your answer! This is not such a big problem btw.

**Comment by dempfi** [comment]
Hey guys, I believe this issue should be fixed now with latest version of ST3.

**Comment by onomori** [comment]
Hey there, frend! Wanted to say that I'm using the latest updates and I'm still experiencing the issue. Same as above, it's not a big issue but just in case someone else comes this way looking for a quick fix:

![shot001](https://user-images.githubusercontent.com/16868065/30427358-1e69f5be-9982-11e7-8de5-af7128ead32c.png)

1. If you use PackageResourceViewer and extract Ayu, you'll be able to find the ayu directory in Preference > Browse Package.
2. Find the your corresponding sublime-theme file (I'm using ayu-dark so for me it's ayu-dark.sublime-theme
3. Search for `ayu/assets/input-search.png` and a little below it, change `"content_margin": [43, 7, 10, 4]` to `"content_margin": [40, 2, 10, 2]`

![shot002](https://user-images.githubusercontent.com/16868065/30427359-1eaf3278-9982-11e7-8e9d-04d50d666596.png)

**Comment by Keith94** [comment]
Thanks @onomori

I hope we get an official fix for it.
